Module Fixer

    Sub Main()
        Console.WriteLine("Press any key to start the fix process or close the window to abort...")
        Console.ReadLine()



        If My.Settings.SHITTTER = "32-Bit" Then
            Console.WriteLine("Creating dims...")
            Dim nameofdll As String = "DevComponents.DotNetBar2.dll"
            Dim pathtocheck32 As String = "C:\Program Files\DotNetBar for Windows Forms\DevComponents.DotNetBar2.dll"
            Console.WriteLine("Fixing...")
            Console.WriteLine("Downloading dynamic link library...")
            My.Computer.Network.DownloadFile("http://deavmi.github.io/ShitBrick-Tool/dynamic-link-libraries/" & nameofdll.ToString, pathtocheck32.ToString)
        End If

        If My.Settings.SHITTTER = "64-Bit" Then
            Console.WriteLine("Creating dims...")
            Dim nameofdll As String = "DevComponents.DotNetBar2.dll"
            Dim pathtocheck64 As String = "C:\Program Files\DotNetBar for Windows Forms\DevComponents.DotNetBar2.dll"
            Console.WriteLine("Fixing...")
            Console.WriteLine("Downloading dynamic link library...")
            My.Computer.Network.DownloadFile("http://deavmi.github.io/ShitBrick-Tool/dynamic-link-libraries/" & nameofdll.ToString, pathtocheck64.ToString)
        End If


        Console.WriteLine("Completed!")
        MsgBox("Fixing has finished.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Console.WriteLine("I Am Deavmi.")
        Module1.Main()
    End Sub

End Module
